const data = [
  { id: 'noticia1', title: 'reunión de padres', date: '2018-15-10', content: 'Hoy tuvimos nuestra última reunión de padres de familia donde entregamos con gran alegría los informes finales. Estamos muy orgullosos por el esfuerzo y la dedicación de los niños. Todos obtuvieron excelentes resultados. Gracias a los padres por la asistencia y compromiso que tuvieron todo el año.' },
  { id: 'noticia2', title: 'programa de emprendimiento', date: '2018-15-10', content: 'Les contamos que hoy terminamos con gran satisfacción la recolección de tapas y de periódico. Agradecemos a todas las familias la colaboración para ayudar a la fundación “María José” y para la compra de las semillas de nuestra huerta.' },
  { id: 'noticia3', title: 'ensayos para la presentación de fin de año', date: '2018-15-10', content: 'A los niños que no utilizan el transporte, se les prestará un servicio de transporte especial trasladándolos al teatro en la mañana y trayéndolos al jardín a medio día. Para contar con este servicio, deben estar en el Jardín a más tardar a las 7:30 a.m. y ser recogidos a la 1:15 p.m. Estos días no habrá actividades en la tarde para ningún curso.' },
  { id: 'noticia4', title: 'presentación de fin de año', date: '2018-15-10', content: 'El próximo viernes 22 de junio será nuestra presentación final titulada “Grimm´s en los olímpicos”. Los esperamos a todos con sus familias. Ya tenemos a la venta las boletas! Quienes quieran adquirirlas con anterioridad pueden mandar comprarlas con los niños. Valor de la boleta: $20.000.' },
  { id: 'noticia5', title: 'matrículas ordinarias', date: '2018-15-10', content: 'De 8:00 a.m. a 12:00 m Las matrículas extraordinarias serán únicamente el JUEVES 5 de julio con un recargo del 20% sobre el costo de la matrícula ordinaria. Les recordamos que es indispensable estar a paz y salvo y tener la Tarjeta Diners habilitada para el cargo de pensiones del año 2018-2019.' },
  { id: 'noticia6', title: 'ceremonia de grado', date: '2018-15-10', content: '(Cambiamos de fecha por el partido de Colombia el 28) A las 10:30 a.m. se realizará en el teatro del Jardín, la graduación de nuestros alumnos de P-Transición. Deben asistir con su uniforme de diario, con excelente presentación. Los asistentes deben parquear en CAFAM.' }
];

export default data;
